/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

import Paquete.Utility;
import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author kevin
 */
public class Home extends javax.swing.JFrame {

 
    JLabel[] ListaEscudos;
    JLabel[] ListaGrado;
    private Object content;
    
    
    
    @SuppressWarnings("empty-statement")
    public Home() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        Utility.SetImageLabel(jLabel1, "src/imagen/Fondo base.png");
        
        this.repaint();
        
       ListaEscudos = new JLabel[] {Escudo0, Escudo1, Escudo2, Escudos3, Escudos4, Escudos5, Escudos6, Escudos7, Escudos8, Escudos9, Escudos10, Escudos11, Escudos12, Escudos13};
        
                
        for(int x = 0; x < 14; x ++) {
            Utility.SetImageLabel(ListaEscudos[x], "src/Imagen/LauncherButton"+ x+".png");
        }
        
       Showpanel();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        Container2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Escudo0 = new javax.swing.JLabel();
        Escudo1 = new javax.swing.JLabel();
        Escudo2 = new javax.swing.JLabel();
        Escudos3 = new javax.swing.JLabel();
        Escudos5 = new javax.swing.JLabel();
        Escudos4 = new javax.swing.JLabel();
        Escudos6 = new javax.swing.JLabel();
        Escudos7 = new javax.swing.JLabel();
        Escudos8 = new javax.swing.JLabel();
        Escudos9 = new javax.swing.JLabel();
        Escudos10 = new javax.swing.JLabel();
        Escudos11 = new javax.swing.JLabel();
        Escudos12 = new javax.swing.JLabel();
        Escudos13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1530, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1530, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1530, 1080));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setOpaque(false);

        Container2.setOpaque(false);

        javax.swing.GroupLayout Container2Layout = new javax.swing.GroupLayout(Container2);
        Container2.setLayout(Container2Layout);
        Container2Layout.setHorizontalGroup(
            Container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1560, Short.MAX_VALUE)
        );
        Container2Layout.setVerticalGroup(
            Container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 1560, 880));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 14));

        Escudo0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton0.png"))); // NOI18N
        Escudo0.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo0.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo0.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudo0);

        Escudo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton1.png"))); // NOI18N
        Escudo1.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo1.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudo1);

        Escudo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton2.png"))); // NOI18N
        Escudo2.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudo2.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudo2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudo2);

        Escudos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton3.png"))); // NOI18N
        Escudos3.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos3.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos3);

        Escudos5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton6.png"))); // NOI18N
        Escudos5.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos5.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos5.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos5);

        Escudos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton5.png"))); // NOI18N
        Escudos4.setToolTipText("");
        Escudos4.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos4.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos4);

        Escudos6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton7.png"))); // NOI18N
        Escudos6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Escudos6.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos6.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos6.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos6);

        Escudos7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton8.png"))); // NOI18N
        Escudos7.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos7.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos7.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos7);

        Escudos8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton9.png"))); // NOI18N
        Escudos8.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos8.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos8.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos8);

        Escudos9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton10.png"))); // NOI18N
        Escudos9.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos9.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos9.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos9);

        Escudos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton11.png"))); // NOI18N
        Escudos10.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos10.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos10.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos10);

        Escudos11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton12.png"))); // NOI18N
        Escudos11.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos11.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos11.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos11);

        Escudos12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LauncherButton13.png"))); // NOI18N
        Escudos12.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos12.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos12.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos12);

        Escudos13.setMaximumSize(new java.awt.Dimension(100, 100));
        Escudos13.setMinimumSize(new java.awt.Dimension(100, 100));
        Escudos13.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(Escudos13);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 1560, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Fondo base.png"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void Showpanel () {
        Page1 p1 = new Page1();

        p1.setSize(1560, 880);
        p1.setLocation(0,0);


        Container.removeAll();
        Container.add(p1,  BorderLayout.CENTER);
        Container.revalidate();
        Container.repaint();

        }
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    public void SetImageLabel (JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        labelName.repaint();
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Container2;
    private javax.swing.JLabel Escudo0;
    private javax.swing.JLabel Escudo1;
    private javax.swing.JLabel Escudo2;
    private javax.swing.JLabel Escudos10;
    private javax.swing.JLabel Escudos11;
    private javax.swing.JLabel Escudos12;
    private javax.swing.JLabel Escudos13;
    private javax.swing.JLabel Escudos3;
    private javax.swing.JLabel Escudos4;
    private javax.swing.JLabel Escudos5;
    private javax.swing.JLabel Escudos6;
    private javax.swing.JLabel Escudos7;
    private javax.swing.JLabel Escudos8;
    private javax.swing.JLabel Escudos9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
    
}
